#!/bin/bash


list=$(buku -p -f 1);

while read -r line; do
    index=$(echo "$line" | cut -f 1);
    url=$(echo "$line" | cut -f 2);
    status=$(curl -sI "$url" | grep "HTTP" | cut -d " " -f 2);

    if [ 200 != "$status" ]; then
        echo ${index} | buku --tag + "expired" -u;
    fi

    sleep 2
done <<< "$list"
